packages:
  - apps/*
  - packages/*
  - fixtures/*
  - test
  - website
overrides:
  '@typespec/bundler>@typespec/compiler': 1.12.0
allowBuilds:
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true
