openapi: 3.0.3
info:
  title: Self-referencing Schema Minimal
  version: 1.0.0
paths:
  /categories:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
components:
  schemas:
    Category:
      type: object
      required: [id, name]
      properties:
        id:
          type: string
        name:
          type: string
        parent:
          $ref: "#/components/schemas/Category"