import { createRoute, z } from '@hono/zod-openapi'

// Generated by hono-takibi from OpenAPI spec (no custom messages)
export const createUserRoute = createRoute({
  method: 'post',
  path: '/users',
  operationId: 'createUser',
  request: {
    body: {
      content: {
        'application/json': {
          schema: z
            .object({
              name: z.string().min(3).max(20),
              email: z.email(),
              age: z.int().min(0).max(150),
            })
            .openapi({ required: ['name', 'email', 'age'] }),
        },
      },
    },
  },
  responses: {
    201: {
      description: 'Created',
      content: {
        'application/json': {
          schema: z.object({
            id: z.int(),
            name: z.string(),
            email: z.string(),
            age: z.int(),
          }),
        },
      },
    },
    422: {
      description: 'Validation Error (RFC 9457 Problem Details)',
      content: {
        'application/json': {
          schema: z.object({
            type: z.string(),
            title: z.string(),
            status: z.int(),
            detail: z.string(),
            errors: z.array(
              z.object({
                pointer: z.string(),
                detail: z.string(),
              }),
            ),
          }),
        },
      },
    },
  },
})
