openapi: 3.0.3
info:
  title: JWT 2段階認証 API
  version: "1.0.0"
servers:
  - url: http://localhost:8080/api
paths:
  /auth/login:
    post:
      summary: ユーザー認証（ログイン）と2段階認証開始
      description: >
        ユーザー名とパスワードによる認証を行い、認証成功の場合は2段階認証用の一時トークンを返却します。
      requestBody:
        description: ユーザー認証情報
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "user@example.com"
                password:
                  type: string
                  example: "password123"
              required:
                - username
                - password
      responses:
        '200':
          description: 認証成功、2段階認証コードの入力が必要
          content:
            application/json:
              schema:
                type: object
                properties:
                  temp_token:
                    type: string
                    description: 2段階認証用の一時トークン
                  message:
                    type: string
                    example: "2段階認証コードの入力が必要です。"
        '401':
          description: 認証失敗（無効なユーザー名またはパスワード）
  /auth/verify-2fa:
    post:
      summary: 2段階認証コードの検証とJWT発行
      description: >
        一時トークンと2段階認証コードを受け取り、コードが正しければJWT形式のアクセストークンを返却します。
      requestBody:
        description: 2段階認証情報
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                temp_token:
                  type: string
                  description: ログイン時に発行された一時トークン
                code:
                  type: string
                  description: ユーザーが入力した2段階認証コード
              required:
                - temp_token
                - code
      responses:
        '200':
          description: 2段階認証成功、JWTアクセストークン発行
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: JWT形式のアクセストークン
                  token_type:
                    type: string
                    example: "Bearer"
        '401':
          description: 2段階認証失敗（無効なコードまたは一時トークン）
  /protected:
    get:
      summary: JWT認証が必要な保護されたエンドポイント
      security:
        - bearerAuth: []
      responses:
        '200':
          description: アクセストークンが有効な場合の正常なレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    example: "保護されたデータへのアクセスに成功しました。"
        '401':
          description: アクセストークンが無効または存在しない場合
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
