openapi: 3.0.3
info:
  title: JWT Two-Factor Authentication API
  version: "1.0.0"
servers:
  - url: https://api.example.com
paths:
  /auth/login:
    post:
      summary: "Primary Authentication"
      description: >
        Authenticate using your username and password to receive a temporary token for two-factor authentication.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: yourpassword
              required:
                - username
                - password
      responses:
        '200':
          description: "Successful authentication. A temporary token for two-factor authentication is returned."
          content:
            application/json:
              schema:
                type: object
                properties:
                  tempToken:
                    type: string
                    description: "Temporary token for two-factor authentication"
                    example: temporary-token-string
        '401':
          description: "Authentication failed."
  /auth/verify:
    post:
      summary: "Two-Factor Authentication Verification"
      description: >
        Validate the temporary token obtained during primary authentication and the one-time password (OTP) to receive a JWT.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tempToken:
                  type: string
                  description: "Temporary token from the primary authentication step"
                  example: temporary-token-string
                otp:
                  type: string
                  description: "One-Time Password"
                  example: "123456"
              required:
                - tempToken
                - otp
      responses:
        '200':
          description: "Two-factor authentication successful. A JWT is returned."
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: "JWT token"
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        '401':
          description: "Two-factor authentication failed."
  /protected:
    get:
      summary: "Access Protected Resource"
      description: >
        This endpoint is accessible only to users with a valid JWT.
        Include the header `Authorization: Bearer {token}` in your request.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: "Resource accessible by authenticated users."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "This is a protected resource."
        '401':
          description: "Unauthorized access."
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
