openapi: 3.0.0
info:
  version: 1.0.0
  title: zod string
  description: zod string
servers:
  - url: v1
components:
  schemas: {}
  parameters: {}
paths:
  /string:
    get:
      description: zod string
      summary: zod string
      responses:
        "200":
          description: zod string
          content:
            application/json:
              schema:
                type: object
                properties:
                  max_string:
                    type: string
                    maxLength: 5
                  min_string:
                    type: string
                    minLength: 5
                  length_string:
                    type: string
                    minLength: 5
                    maxLength: 5
                  email_string:
                    type: string
                    format: email
                  url_string:
                    type: string
                    format: uri
                  uuid_string:
                    type: string
                    format: uuid
                  nanoid_string:
                    type: string
                  cuid_string:
                    type: string
                    format: cuid
                  ulid_string:
                    type: string
                    format: ulid
                  regex_string:
                    type: string
                    pattern: ^d+$
                  includes_string:
                    type: string
                  startsWith_string:
                    type: string
                  endsWith_string:
                    type: string
                  datetime_string:
                    type: string
                    format: date-time
                  ip_string:
                    type: string
                    format: ip
                  cidr_string:
                    type: string
                  trim_string:
                    type: string
                  toLowerCase_string:
                    type: string
                  toUpperCase_string:
                    type: string
                  date_string:
                    type: string
                    format: date
                  time_string:
                    type: string
                  duration_string:
                    type: string
                  base64_string:
                    type: string
                required:
                  - max_string
                  - min_string
                  - length_string
                  - email_string
                  - url_string
                  - uuid_string
                  - nanoid_string
                  - cuid_string
                  - ulid_string
                  - regex_string
                  - includes_string
                  - startsWith_string
                  - endsWith_string
                  - datetime_string
                  - ip_string
                  - cidr_string
                  - trim_string
                  - toLowerCase_string
                  - toUpperCase_string
                  - date_string
                  - time_string
                  - duration_string
                  - base64_string
