openapi: 3.0.0
info:
  version: 1.0.0
  title: zod literal
  description: zod literal
servers:
  - url: v1
components:
  schemas: {}
  parameters: {}
paths:
  /primitive:
    get:
      description: zod primitive
      summary: zod primitive
      responses:
        "200":
          description: zod literal
          content:
            application/json:
              schema:
                type: object
                properties:
                  tuna_literal:
                    type: string
                    enum:
                      - tuna
                  twelve_literal:
                    type: number
                    enum:
                      - 12
                  twobig_literal:
                    type: bigint
                    enum:
                      - 2
                  true_literal:
                    type: boolean
                    enum:
                      - true
                required:
                  - tuna_literal
                  - twelve_literal
                  - twobig_literal
                  - true_literal
