openapi: 3.0.0
info:
  version: 1.0.0
  title: zod passthrough()
  description: zod passthrough()
servers:
  - url: v1
components:
  schemas: {}
  parameters: {}
paths:
  /passthrough:
    get:
      description: zod passthrough
      summary: zod passthrough
      responses:
        "200":
          description: zod passthrough
          content:
            application/json:
              schema:
                type: object
                properties:
                  test:
                    type: string
                required:
                  - test
                additionalProperties: true
