openapi: 3.1.0
info:
  title: Edge Case API
  version: 1.0.0
paths:
  /polymorphic:
    post:
      summary: Polymorphic object with discriminator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
              discriminator:
                propertyName: type
                mapping:
                  cat: '#/components/schemas/Cat'
                  dog: '#/components/schemas/Dog'
      responses:
        '200':
          description: OK

  /search:
    get:
      summary: Search with complex query
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
        - name: filter
          in: query
          schema:
            anyOf:
              - type: string
              - type: array
                items:
                  type: string
        - name: exclude
          in: query
          schema:
            not:
              type: number
      responses:
        '200':
          description: OK

  /multi-step:
    put:
      summary: Multi-step object definition using allOf
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/Base'
                - type: object
                  properties:
                    step:
                      type: integer
                      minimum: 1
                      maximum: 3
      responses:
        '204':
          description: No Content

components:
  schemas:
    Animal:
      type: object
      required:
        - type
      properties:
        type:
          type: string
      discriminator:
        propertyName: type

    Cat:
      allOf:
        - $ref: '#/components/schemas/Animal'
        - type: object
          properties:
            livesLeft:
              type: integer
              minimum: 0
              maximum: 9

    Dog:
      allOf:
        - $ref: '#/components/schemas/Animal'
        - type: object
          properties:
            barkLevel:
              type: string
              enum: [quiet, normal, loud]

    Base:
      type: object
      required: [id]
      properties:
        id:
          type: string
          format: uuid
        metadata:
          type: object
          nullable: true
          additionalProperties:
            type: string
