openapi: 3.0.0
info:
  version: 1.0.0
  title: zod number
  description: zod number
servers:
  - url: v1
components:
  schemas: {}
  parameters: {}
paths:
  /number:
    get:
      description: zod number
      summary: zod number
      responses:
        "200":
          description: zod number
          content:
            application/json:
              schema:
                type: object
                properties:
                  gt5_number:
                    type: number
                    minimum: 5
                    exclusiveMinimum: true
                  gte5_number:
                    type: number
                    minimum: 5
                  lt5_number:
                    type: number
                    maximum: 5
                    exclusiveMaximum: true
                  lte5_number:
                    type: number
                    maximum: 5
                  int_number:
                    type: integer
                  positive_number:
                    type: number
                    minimum: 0
                    exclusiveMinimum: true
                  nonnegative_number:
                    type: number
                    minimum: 0
                  negative_number:
                    type: number
                    maximum: 0
                    exclusiveMaximum: true
                  nonpositive_number:
                    type: number
                    maximum: 0
                  multipleOf5_number:
                    type: integer
                  finite_number:
                    type: number
                  safe_number:
                    type: number
                    minimum: -9007199254740991
                    maximum: 9007199254740991
                  message_number:
                    type: number
                    maximum: 5
                required:
                  - gt5_number
                  - gte5_number
                  - lt5_number
                  - lte5_number
                  - int_number
                  - positive_number
                  - nonnegative_number
                  - negative_number
                  - nonpositive_number
                  - multipleOf5_number
                  - finite_number
                  - safe_number
                  - message_number
