name: Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.1

      - uses: voidzero-dev/setup-vp@v1.12.0
        with:
          node-version: '22'
          cache: true

      - run: vp install

      - run: vp run hono-takibi#build

      - run: vp check

      - run: vp test --coverage
